project_id = "tourfurr"

[api]
port = 54321

[auth]
site_url = "http://localhost:5173"

[auth.external.smtp]
enabled = true
host = "smtp.resend.com"
port = 465
user = "resend"
pass = "env(SMTP_PASS)"

# Если CLI снова ругнется на "auth", попробуйте удалить эти две строки ниже:
# admin_email = "team@tourfurr.camp"
# sender_name = "TourFurr 2026"